# install docker

- name: Install Docker
  hosts: all
  become: yes

  tasks:

  - name: uninstall old versions Docker
    apt: 
      pkg: docker docker-engine docker.io 
      state: absent
  
  - name: Install Docker
    apt: 
      name: docker.io

  - name: Make sure docker is running
    service:
      name: docker      
      state: started

  - name: Enabled docker systemctl
    service:
      name: docker
      enabled: yes

  - name: Install or update pip
    apt:
      name: python3-pip
      state: latest
      
  - name: Install bottle python package
    pip:
      name: docker

  - name: Install gitlab-runner
    apt:
      name: gitlab-runner
      state: latest

#  - name: Create a docker container
#    docker_container:
#      name: gitlab
#      image: gitlab/gitlab-runner
#      ports:
#        - "82:8080"
 
      #  - name: shell command to run Docker container
      #    shell: sudo docker run -dp 80:80 store/gitlab/gitlab-ee:11.10.4-ee.0 # store/gitlab/gitlab-ee:11.10.4-ee.0
